name: example
description: "Ejemplo de uso del paquete fancy_titles."
publish_to: "none"
version: 1.0.1

environment:
  sdk: ^3.8.0

dependencies:
  fancy_titles:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
