name: fancy_titles
description: "Una serie de splash screens animados para Flutter basados en mis juegos y animes favoritos."
version: 1.0.8
homepage:

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  generate: true

  assets:
    - test/fixtures/

  fonts:
    - family: ManiaZoneCard
      fonts:
        - asset: packages/fancy_titles/fonts/mania-zone-card.ttf
          weight: 400
    - family: EVAMatisseClassic
      fonts:
        - asset: packages/fancy_titles/fonts/EVA-Matisse_Classic.ttf
          weight: 400
    - family: Persona
      fonts:
        - asset: packages/fancy_titles/fonts/Persona-5-Menu-Font-Prototype.ttf
          weight: 400
    - family: BouCollege
      fonts:
        - asset: packages/fancy_titles/fonts/Bou-College-Font.ttf
          weight: 400
